apiVersion: ENC[AES256_GCM,data:bs8=,iv:ku0aZh1rOT++IPOUsjHUASDIcflV2SXLy08rNfU68N4=,tag:cNb930RFPg6OLROT6hu1vw==,type:str]
kind: ENC[AES256_GCM,data:gnnhj5Pc,iv:3vFbSSMfMCkgA+P/2WNuIG2WqNdARqJMr7mn/aImXbw=,tag:YDYnxHwddBuBypLQcrbShQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:I4zs4/08R3l8okbG/90q,iv:w8I10UvqLHd4Y3w8mt/c+ODMJyQHYPIOMoki8SO61F4=,tag:w+bUIZ4mY98MS/Eb2AZbrQ==,type:str]
    namespace: ENC[AES256_GCM,data:ShExeB+17NXOUA==,iv:9HeLmE/83DrWgqp28jn4g/07KsDHr6zvzn/FTIXlPME=,tag:6D6YbCnLVRqCLIkHuObpDg==,type:str]
type: ENC[AES256_GCM,data:sOp3NXSH,iv:kpoiKZpbhRoxRM1cWu1BNcQNRBIFGZjugyslbV9/qxk=,tag:xJAX+1HU+gbY9R0EDqWhew==,type:str]
stringData:
    SEARXNG_SECRET_KEY: ENC[AES256_GCM,data:nppSg3Y9WfAaEiVw0ZlzUeYzmDqkuwhUfw==,iv:/aamfxMoCfwLkaCS9mqOHykHJIA2wvWjg2ij3hE7DXU=,tag:3w1Tli9Pj3wx+xJE62RExw==,type:str]
sops:
    age:
        - recipient: age13yemwqzta484kj4jx343qgdxuqj0qpnvyjh7nm9de064uc9waejqnngqmg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxOVZ5MktHSjJIeGZoZHlB
            VFg2NEZVL2JkOTFFZHcwaTMyMjVOUTBkVlVZCldzMVU3UnJvWFdqdkJ0ZmJuTS9I
            aTR6d1lBcXBXdEZaeVNTREEzWlZOSlkKLS0tICs0TWx3OFRQU0paZDJpMUx5d1Vp
            VDR6TkZqdXFvUEo2czdqZVZJRGdVa1UKlOvzp9FkYNeED2r9+5HAv3hOjkNboReq
            B1rZmqsib8lirpvi9tfLcGETuD61jM0y+6uXW3g2s/c3VZhkhIWxgg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-12T04:53:52Z"
    mac: ENC[AES256_GCM,data:GGd6zYZfcJJq4m/PidX8eNF7S8B7ngvwbVNXQwI+34+pZwug7mAVrUEkVr42eZBvFVqSfViiBmEE3UH7aMNIGWBsFZ+hrYig9th6uiOWI0f9d+Vy47TByOcMgyD06y7gsn3+JL8g9q47hcErwh15xUHnidqYUEeV1UwNZndxJIs=,iv:Tc/as4S0CcjIwFMCWt49VF+T5QbNlXdhM1sB6vQSAGo=,tag:ifWdX7biK0GUqZfdc+evyg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
